server:
  port: 8000

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka