spring:
  application:
    name: discover
  profiles:
    active: default

server:
  port: 8761
  hostname: discovery-host
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
